version: '2'
services:
  cccar:
    image: jokyip/cccar
    external_links:
      - cccar_mongo
    networks:
      - cccarmongo_default
    ports:
      - 8030:1337
    volumes:
      - ${COMPOSEROOT}/cccar/config/env/development.coffee:/usr/src/app/config/env/development.coffee
      - /etc/ssl/certs:/etc/ssl/certs
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - ${COMPOSEROOT}/cccar/entrypoint.sh:/usr/src/app/entrypoint.sh
      - ${COMPOSEROOT}/cccar:/usr/src/app
    environment:
      SERVICE_NAME: cccar  
    env_file: ./.env
    entrypoint: top -b -d 1000

networks:
  cccarmongo_default:
    external: true