version: '2'
services:
  cccar_mongo:
    image: mongo
    container_name: cccar_mongo
    hostname: cccar_mongo
    ports:
      - 27017
    volumes:
      - ${COMPOSEROOT}/cccar_mongodata:/data/db
    command: mongod --directoryperdb
    env_file: ../.env

  cccar:
    depends_on:
      - cccar_mongo
    image: jokyip/cccar
    container_name: cccar
    hostname: cccar
    ports:
      - 8030:1337
    volumes:
      - ${COMPOSEROOT}/cccar/config/env/development.coffee:/usr/src/app/config/env/development.coffee
      - ${COMPOSEROOT}/cccar/www/js/config/development.coffee:/usr/src/app/www/js/config/development.coffee
      - /etc/ssl/certs:/etc/ssl/certs
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - ${COMPOSEROOT}/cccar/entrypoint.sh:/usr/src/app/entrypoint.sh
      - ${COMPOSEROOT}/cccar:/usr/src/app
    env_file: ../.env
    entrypoint: top -b -d 1000
