env = require './env.coffee'

window.Promise = require 'bluebird'
window._ = require 'lodash'
window.$ = require 'jquery'
window.$.deparam = require 'jquery-deparam'

require 'ngCordova'
require 'AngularJS-Toaster'
require 'angular-activerecord'
require 'angular-touch'
require 'tagDirective'
require 'angular-translate'
require 'angular-translate-loader-static-files'
require 'util.auth'
require 'sails-auth'
require './templates.js'
require './app.coffee'
require './controller.coffee'
require './model.coffee'
require './locale.coffee'
require './platform.coffee'